export const state = {
  leadsData: null,
  oppData: null,
  activeResults: [],
  inactiveResults: [],
  unassignedResults: [],
  masterMap: new Map(),
  changeLog: [],
  realtorOwnerMap: new Map(),
  currentMode: 'active',
  sortCol: 'cnt',
  sortDir: -1,
  dbConnected: false,
  loReferenceMap: new Map(),
  loActiveResults: [],
  loInactiveResults: [],
  loUnassignedResults: [],
  loMasterMap: new Map(),
  loCurrentMode: 'active',
  loSortCol: 'cnt',
  loSortDir: -1,
  callsData: [],
  zoomData: []
};
